# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20171118_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='finish',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
